Repository KEA-ReNov8/Befly-FE, pull requests merged in 2025-06, with the labels that each got.

#45 [feat/KAN-182] ai mate & report api 연결 / [fix] social login 오류 수정
  .gitignore
  package-lock.json
  package.json
  src/app/routes/router.jsx
  src/pages/chat/components/Chat.jsx
  src/pages/chat/components/ChatForm.jsx
  src/pages/chat/components/ChatMessage.jsx
  src/pages/chat/components/ProgressBar.jsx
  src/pages/chat/components/SideBar.jsx
  src/pages/chat/components/SideBarButton.jsx
  src/pages/chat/components/SuccessModal.jsx
  src/pages/chat/feature/hooks/mutate/useCreateNewChatMutation.js
  src/pages/chat/feature/hooks/mutate/useDeleteChatSession.js
  src/pages/chat/feature/hooks/mutate/useSendChatMutation.js
  src/pages/chat/feature/hooks/mutate/useTest.jsx
  src/pages/chat/feature/hooks/query/useChatHistoryQuery.js
  src/pages/chat/feature/hooks/query/useChatSessionListQuery.js
  src/pages/chat/feature/hooks/query/useConsultResultQuery.js
  src/pages/chat/feature/hooks/query/useTest.jsx
  src/pages/chat/feature/store/useChatStore.js
  src/pages/chat/feature/store/useTestStore.js
  src/pages/chat/feature/utils/createNewSession.js
  src/pages/chat/feature/utils/sendChat.js
  src/pages/chat/style/chatStyle.jsx
  src/pages/error/ErrorPage.jsx
  src/pages/login/feature/utils/handleOnSubmit.js
  src/pages/my/components/DeleteModal.jsx
  src/pages/my/components/WorryList.jsx
  src/pages/my/components/WorryPost.jsx
  src/pages/post/components/mindreport/AIAnalysisPage.jsx
  src/pages/post/components/mindreport/AIOpinionPage.jsx
  src/pages/post/components/mindreport/AnalysisCardsPage.jsx
  src/pages/post/components/mindreport/MindReportSection.jsx
  src/pages/post/ui/SharePostPage.jsx
  src/pages/report/components/Advise.jsx
  src/pages/report/components/Analysis.jsx
  src/pages/report/components/Report.jsx
  src/pages/report/components/ScoreCard.jsx
  src/pages/report/feature/hook/useGetReportQuery.js
  src/pages/report/ui/ReportPage.jsx
  src/shared/apis/instance/index.js
  src/shared/ui/TopBar/TopBar.jsx
  src/shared/ui/TopBar/WorryModal.jsx
Labels: feat, 동윤

#58 [fix/KAN-187]/social
  src/pages/login/ui/LoginPage.jsx
Labels: bug

#60 [Revert ][fix/KAN-187] social login
  src/app/routes/ProtectedRouter.jsx
  src/app/routes/router.jsx
  src/pages/login/ui/LoginPage.jsx
Labels: fix

#70 [refactor/KAN-191] 디자인 및 애니메이션 조정
  src/pages/chat/components/Chat.jsx
  src/pages/chat/components/SideBar.jsx
  src/pages/chat/feature/hooks/mutate/useCreateNewChatMutation.js
  src/pages/chat/feature/hooks/mutate/useDeleteChatSession.js
  src/pages/chat/feature/hooks/query/useChatHistoryQuery.js
  src/pages/chat/feature/hooks/query/useChatSessionListQuery.js
  src/pages/home/components/BannerPlaceHolder.jsx
  src/pages/home/components/SectionsContainer.jsx
  src/pages/login/components/SignUpForm.jsx
  src/pages/login/feature/hooks/useLoginMutation.js
  src/pages/login/feature/hooks/useSignupMutation.js
  src/pages/login/feature/hooks/useSocialSignupMutation.js
  src/pages/login/ui/FindPwPage.jsx
  src/pages/login/ui/LoginPage.jsx
  src/pages/login/ui/SelfSignupPage.jsx
  src/pages/login/ui/SignupPage.jsx
  src/pages/my/components/DeleteModal.jsx
  src/pages/my/components/EditProfileModal.jsx
  src/pages/my/components/MyProfile.jsx
  src/pages/my/components/WorryList.jsx
  src/pages/post/ui/FreePostListPage.jsx
  src/pages/post/ui/SharePostListPage.jsx
  src/shared/apis/post/comment.js
  src/shared/assets/lotties/wait.json
  src/shared/ui/PageTransition.jsx
  src/shared/ui/TopBar/TopBar.jsx
  src/shared/ui/TopBar/WorryModal.jsx
  src/shared/ui/lottieComp/Greet.jsx
  src/shared/ui/lottieComp/Success.jsx
  src/shared/ui/lottieComp/Suspend.jsx
  src/shared/ui/lottieComp/wait.jsx
Labels: refactor, 동윤, fix

#71 Refactor/kan 192/게시글 관련 렌더링 조정
  src/pages/post/components/DeleteModal.jsx
  src/pages/post/components/postwrite/CommentListBox.jsx
  src/pages/post/components/postwrite/PostBox.jsx
  src/pages/post/feature/hooks/useCreateFreeCommentMutation.js
  src/pages/post/feature/hooks/useCreateShareCommentMutation.js
  src/pages/post/feature/hooks/useDeleteFreeCommentMutation.js
  src/pages/post/feature/hooks/useDeleteFreePostMutation.js
  src/pages/post/feature/hooks/useDeleteShareCommentMutation.js
  src/pages/post/feature/hooks/useDeleteSharePostMutation.js
  src/pages/post/feature/hooks/useFreeEmpathy.js
  src/pages/post/feature/hooks/useShareEmpathy.js
  src/pages/post/feature/hooks/useUpdateFreeCommentMutation.js
  src/pages/post/feature/hooks/useUpdateFreePostMutation.js
  src/pages/post/feature/hooks/useUpdateShareCommentMutation.js
  src/pages/post/feature/hooks/useUpdateSharePostMutation.js
  src/pages/post/ui/FreePage.jsx
  src/shared/apis/post/comment.js
  src/shared/apis/post/empathy.js
  src/shared/apis/post/share.js
  vite.config.js
Labels: refactor
